language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: src/.vuepress/dist
  github_token: rb2N9bNflF7Di1L0JZoQ7g
  keep_history: true
  on:
    branch: develop
