language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
  - cd src/.vuepress/dist
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push -f git@github.com:LEEKYOUNGHWA/LEEKYOUNGHWA.github.io.git master
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: src/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
